### ISSUE TITLE
Cant open modal for leapard input.

### ISSUE THREAD

**Issue by joseym** [jbeluch/xbmcswift2#121]
I have the following:

``` python
@plugin.route('/search')
def search():
    search_string = plugin.leopard(heading='Search by Star')
    if search_string:
        url = plugin.url_for(
            'starVids',
            name=search_string
        )
        plugin.redirect(url)
```

which is throwing this error:

```
13:28:12 T:4932767744   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.AttributeError'>
Error Contents: 'Plugin' object has no attribute 'leopard'
Traceback (most recent call last):
  File "/.xbmc/addons/plugin.video.starplayground/addon.py", line 105, in <module>
    plugin.run()
  File "/.xbmc/addons/xbmcswift2-xbmc-dist-2.4.0/lib/xbmcswift2/plugin.py", line 332, in run
    items = self._dispatch(self.request.path)
  File "/.xbmc/addons/xbmcswift2-xbmc-dist-2.4.0/lib/xbmcswift2/plugin.py", line 306, in _dispatch
    listitems = view_func(**items)
  File "/.xbmc/addons/plugin.video.starplayground/addon.py", line 95, in search
    search_string = plugin.leopard(heading='search')
AttributeError: 'Plugin' object has no attribute 'leopard'
-->End of Python script error report<--
13:28:12 T:4416639744   ERROR: GetDirectory - Error getting plugin://plugin.video.starplayground/search
13:28:12 T:4416639744   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.starplayground/search) failed
```

**Comment by joseym** [comment]
I guess that would be because, at least on the version I installed within my dev xbmc, `2.4.0`, the attribute name is `keyboard`.

Is the documentation wrong or am I on the wrong version?
