### ISSUE TITLE
Returning Empty List of ListItems in CLI Raises Exception

### ISSUE THREAD

**Issue by cancan101** [jbeluch/xbmcswift2#61]
```
Traceback (most recent call last):
  File "/home/alex/workspace/xbmcswift2/xbmcswift2/cli/cli.py", line 79, in <module>
    main()
  File "/home/alex/workspace/xbmcswift2/xbmcswift2/cli/cli.py", line 76, in main
    manager.run(opts, args[1:])
  File "/home/alex/workspace/xbmcswift2/xbmcswift2/cli/app.py", line 52, in run
    plugin_mgr.run()
  File "/home/alex/workspace/xbmcswift2/xbmcswift2/cli/app.py", line 129, in run
    return handler(self.plugin)
  File "/home/alex/workspace/xbmcswift2/xbmcswift2/cli/app.py", line 164, in interactive
    items = [item for item in once(plugin) if not item.get_played()]
  File "/home/alex/workspace/xbmcswift2/xbmcswift2/cli/app.py", line 156, in once
    display_listitems(items)
  File "/home/alex/workspace/xbmcswift2/xbmcswift2/cli/console.py", line 25, in display_listitems
    label_width = get_max_len(item.get_label() for item in items)
  File "/home/alex/workspace/xbmcswift2/xbmcswift2/cli/console.py", line 14, in get_max_len
    return max(len(item) for item in items)
ValueError: max() arg is an empty sequence
```

**Comment by jbeluch** [comment]
Merged your PR in the develop branch.
